name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: ralphite/action_update_python_project@v2
        with:
            python-version: "3.11"
            test-script: |
                python -m pip install -r ${{ github.workspace }}/tests/requirements.txt
                python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
                cp -r ${{ github.workspace }}/tests ./tests
                pytest
            pypi-token: ${{ secrets.pypi_token }}
            github-user: ralphite
            github-token: ${{ github.token }}
            email-user: ${{ secrets.email_user }}
            email-token: ${{ secrets.email_token }}
            email-server: ${{ secrets.email_server }}
            email-target: ${{ secrets.email_target }}